version: '3.8'

services:

  mongo: 
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_DATABASE="ourtube"
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongodb-express
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - 8081:8081
    depends_on:
      - mongo